<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageId>Genesa.Scynapse.GrainDirectory.Redis</PackageId>
    <Title>Microsoft Scynapse Grain Directory Redis Provider</Title>
    <Description>Microsoft Scynapse Grain Directory implementation that uses Redis</Description>
    <PackageTags>$(PackageTags) Redis Grain Directory</PackageTags>
    <TargetFrameworks>$(DefaultTargetFrameworks)</TargetFrameworks>
    <ScynapseBuildTimeCodeGen>true</ScynapseBuildTimeCodeGen>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="StackExchange.Redis" />
    <PackageReference Include="System.Diagnostics.PerformanceCounter" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="$(SourceRoot)src\Scynapse.Runtime\Scynapse.Runtime.csproj" />
  </ItemGroup>


  <ItemGroup>
    <None Include="README.md" Pack="true" PackagePath="\" />
  </ItemGroup>
</Project>
