<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <PackageId>Genesa.Scynapse.BroadcastChannel</PackageId>
    <Title>Microsoft Scynapse Broadcast Channel Library</Title>
    <Description>Broadcast Channel library for Microsoft Scynapse used both on the client and server.</Description>
    <TargetFrameworks>$(DefaultTargetFrameworks)</TargetFrameworks>
    <ScynapseBuildTimeCodeGen>true</ScynapseBuildTimeCodeGen>
    <ProduceReferenceAssembly>false</ProduceReferenceAssembly>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Scynapse.Runtime\Scynapse.Runtime.csproj" />
  </ItemGroup>
</Project>
