<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <CLRTestKind>BuildAndRun</CLRTestKind>
    <CLRTestPriority>0</CLRTestPriority>
    <BuildAsStandalone>true</BuildAsStandalone>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="TDSVerification.cs" />
  </ItemGroup>
</Project>
