@echo off
REM ============================================
REM DOTNExT Visual Studio Launcher
REM Launches VS 2022 with custom runtime + compiler
REM Generated by Update-DOTNExT.ps1
REM ============================================

SET DOTNET_ROOT=D:\Dev\DOTNExT\src\sdk\artifacts\bin\redist\Release\dotnet
SET DOTNET_MULTILEVEL_LOOKUP=0
SET CORE_ROOT=D:\Dev\DOTNExT\src\runtime\artifacts\tests\coreclr\windows.x64.Release\Tests\Core_Root
SET PATH=%DOTNET_ROOT%;%CORE_ROOT%;%PATH%

REM Critical: Allow debugging unsigned .NET runtime builds
SET VSDebugger_ValidateDotnetDebugLibSignatures=0
SET DOTNET_ReadyToRun=0

echo Starting Visual Studio with DOTNExT...
echo   DOTNET_ROOT=%DOTNET_ROOT%
echo   CORE_ROOT=%CORE_ROOT%
echo   Hive: RoslynDev (experimental)
echo.

start "" "C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\devenv.exe" /rootSuffix RoslynDev %*
