<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>$(TestTargetFrameworks)</TargetFrameworks>
    <ScynapseBuildTimeCodeGen>true</ScynapseBuildTimeCodeGen>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="$(SourceRoot)src\Azure\Scynapse.Streaming.EventHubs\Scynapse.Streaming.EventHubs.csproj" />
    <ProjectReference Include="$(SourceRoot)test\Tester\Tester.csproj" />
    <ProjectReference Include="$(SourceRoot)src\Scynapse.Serialization.NewtonsoftJson\Scynapse.Serialization.NewtonsoftJson.csproj" />
    <ProjectReference Include="$(SourceRoot)test\Misc\TestInternalDtosRefScynapse\TestInternalDtosRefScynapse.csproj" />
    <ProjectReference Include="..\..\src\Scynapse.Serialization.SystemTextJson\Scynapse.Serialization.SystemTextJson.csproj" />
    <ProjectReference Include="..\..\src\Serializers\Scynapse.Serialization.Protobuf\Scynapse.Serialization.Protobuf.csproj" />
    <ProjectReference Include="$(SourceRoot)test\Grains\TestSplitGrainContracts\TestSplitGrainContracts.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.TimeProvider.Testing" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="NSubstitute" />
    <PackageReference Include="NSubstitute.Analyzers.CSharp" />
    <PackageReference Include="CsCheck" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="*.xml" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>