<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <PackageId>Microsoft.Orleans.Runtime</PackageId>
    <Title>Microsoft Orleans Runtime</Title>
    <Description>Core runtime library of Microsoft Orleans that hosts and executes grains within a silo.</Description>
    <TargetFrameworks>$(DefaultTargetFrameworks)</TargetFrameworks>
    <OrleansBuildTimeCodeGen>true</OrleansBuildTimeCodeGen>
    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="$(SourceRoot)src\\Orleans.Core\Orleans.Core.csproj" />
    <ProjectReference Include="$(SourceRoot)src\\Orleans.Core.Abstractions\Orleans.Core.Abstractions.csproj" />
    <ProjectReference Include="$(SourceRoot)src\\Orleans.Serialization\Orleans.Serialization.csproj" />
    <ProjectReference Include="$(SourceRoot)src\\Orleans.Reminders.Abstractions\Orleans.Reminders.Abstractions.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="McMaster.NETCore.Plugins" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
    <PackageReference Include="Microsoft.Extensions.Logging" />
    <PackageReference Include="Microsoft.Extensions.Options" />
    <PackageReference Include="Microsoft.Extensions.Configuration" />
  </ItemGroup>

  <ItemGroup>
    <None Include="README.md" Pack="true" PackagePath="\" />
  </ItemGroup>

</Project>
