<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>UnitTests.SplitGrain.Contracts</RootNamespace>
    <TargetFramework>$(MinTestTargetFramework)</TargetFramework>
    <ScynapseBuildTimeCodeGen>true</ScynapseBuildTimeCodeGen>
    <EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
  </PropertyGroup>

  <ItemGroup>
    <Using Remove="Scynapse.Hosting" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="$(SourceRoot)src\Scynapse.Core.Abstractions\Scynapse.Core.Abstractions.csproj" />
  </ItemGroup>
</Project>
