<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <DefineConstants>$(DefineConstants);AWSUTILS_TESTS</DefineConstants>
    <TargetFrameworks>$(TestTargetFrameworks)</TargetFrameworks>
    <ScynapseBuildTimeCodeGen>true</ScynapseBuildTimeCodeGen>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="$(SourceRoot)src\AWS\Shared\AWSUtils.cs" Link="AWSUtils.cs" />
    <Compile Include="$(SourceRoot)src\AWS\Shared\Storage\DynamoDBStorage.cs" Link="Storage\DynamoDBStorage.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="$(SourceRoot)src\AWS\Scynapse.Clustering.DynamoDB\Scynapse.Clustering.DynamoDB.csproj" />
    <ProjectReference Include="$(SourceRoot)src\AWS\Scynapse.Persistence.DynamoDB\Scynapse.Persistence.DynamoDB.csproj" />
    <ProjectReference Include="$(SourceRoot)src\AWS\Scynapse.Reminders.DynamoDB\Scynapse.Reminders.DynamoDB.csproj" />
    <ProjectReference Include="$(SourceRoot)src\AWS\Scynapse.Streaming.SQS\Scynapse.Streaming.SQS.csproj" />
    <ProjectReference Include="$(SourceRoot)test\TesterInternal\TesterInternal.csproj" />
  </ItemGroup>
</Project>