<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>$(TestTargetFrameworks)</TargetFrameworks>
    <ScynapseBuildTimeCodeGen>true</ScynapseBuildTimeCodeGen>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="$(SourceRoot)src\Scynapse.Streaming.NATS\Scynapse.Streaming.NATS.csproj" />
    <ProjectReference Include="$(SourceRoot)test\Tester\Tester.csproj" />
    <ProjectReference Include="$(SourceRoot)test\TesterInternal\TesterInternal.csproj" />
  </ItemGroup>
</Project>
