<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <ScynapseBuildTimeCodeGen>true</ScynapseBuildTimeCodeGen>
    <TargetFrameworks>$(TestTargetFrameworks)</TargetFrameworks>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="NodaTime" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="$(SourceRoot)src\Scynapse.Serialization\Scynapse.Serialization.csproj" />
    <ProjectReference Include="$(SourceRoot)src\Scynapse.Serialization.FSharp\Scynapse.Serialization.FSharp.csproj" />
    <ProjectReference Include="$(SourceRoot)test\Tester\Tester.csproj" />
    <ProjectReference Include="$(SourceRoot)test\Misc\TestInternalDtosRefScynapse\TestInternalDtosRefScynapse.csproj" />
  </ItemGroup>
</Project>
