<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageId>Genesa.Scynapse.Reminders.AdoNet</PackageId>
    <Title>Microsoft Scynapse ADO.NET Reminders Provider</Title>
    <Description>Microsoft Scynapse reminders provider backed by ADO.NET</Description>
    <PackageTags>$(PackageTags) ADO.NET SQL MySQL PostgreSQL Oracle</PackageTags>
    <TargetFrameworks>$(DefaultTargetFrameworks)</TargetFrameworks>
    <ScynapseBuildTimeCodeGen>true</ScynapseBuildTimeCodeGen>
  </PropertyGroup>

  <PropertyGroup>
    <AssemblyName>Scynapse.Reminders.AdoNet</AssemblyName>
    <RootNamespace>Scynapse.Reminders.AdoNet</RootNamespace>
    <DefineConstants>$(DefineConstants);REMINDERS_ADONET</DefineConstants>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="..\Shared\Storage\*.cs" LinkBase="Storage" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="$(SourceRoot)src\Scynapse.Runtime\Scynapse.Runtime.csproj" />
    <ProjectReference Include="$(SourceRoot)src\Scynapse.Reminders\Scynapse.Reminders.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="README.md" Pack="true" PackagePath="\" />
  </ItemGroup>
</Project>
