<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFrameworks>$(TestTargetFrameworks)</TargetFrameworks>
    <ScynapseBuildTimeCodeGen>true</ScynapseBuildTimeCodeGen>
    <OutputPath Condition=" '$(DistributedTestsOutputPath)'!='' ">$(DistributedTestsOutputPath)/DistributedTests.Server</OutputPath>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="..\secrets.json" Link="secrets.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="$(SourceRoot)src\Azure\Scynapse.Clustering.AzureStorage\Scynapse.Clustering.AzureStorage.csproj" />
    <ProjectReference Include="$(SourceRoot)src\Scynapse.Persistence.Memory\Scynapse.Persistence.Memory.csproj" />
    <ProjectReference Include="$(SourceRoot)src\Scynapse.Server\Scynapse.Server.csproj" />
    <ProjectReference Include="$(SourceRoot)test\DistributedTests\DistributedTests.Common\DistributedTests.Common.csproj" />
    <ProjectReference Include="$(SourceRoot)test\DistributedTests\DistributedTests.Grains\DistributedTests.Grains.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" />
    <PackageReference Include="Microsoft.Extensions.Logging.Console" />
    <PackageReference Include="System.CommandLine" />
  </ItemGroup>

</Project>
