<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageId>Genesa.Scynapse.Serialization.SystemTextJson</PackageId>
    <TargetFrameworks>$(DefaultTargetFrameworks);netstandard2.1</TargetFrameworks>
    <PackageDescription>System.Text.Json integration for Scynapse.Serialization</PackageDescription>
    <ScynapseBuildTimeCodeGen>true</ScynapseBuildTimeCodeGen>
    <IsScynapseFrameworkPart>false</IsScynapseFrameworkPart>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Scynapse.Serialization\Scynapse.Serialization.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="README.md" Pack="true" PackagePath="\" />
  </ItemGroup>
</Project>
