<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <PackageId>Genesa.Scynapse.Persistence.AzureStorage</PackageId>
    <Title>Microsoft Scynapse Azure Storage Persistence Provider</Title>
    <Description>Microsoft Scynapse persistence providers backed by Azure Storage</Description>
    <PackageTags>$(PackageTags) Azure Table Blob Storage</PackageTags>
    <TargetFrameworks>$(DefaultTargetFrameworks)</TargetFrameworks>
    <AssemblyName>Scynapse.Persistence.AzureStorage</AssemblyName>
    <RootNamespace>Scynapse.Persistence.AzureStorage</RootNamespace>
    <ScynapseBuildTimeCodeGen>true</ScynapseBuildTimeCodeGen>
    <DefineConstants>$(DefineConstants);SCYNAPSE_PERSISTENCE</DefineConstants>
    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="..\Shared\Storage\AzureBlobUtils.cs" Link="Storage\AzureBlobUtils.cs" />
    <Compile Include="..\Shared\Storage\AzureStorageOperationOptions.cs" Link="Storage\AzureStorageOperationOptions.cs" />
    <Compile Include="..\Shared\Storage\AzureStoragePolicyOptions.cs" Link="Storage\AzureStoragePolicyOptions.cs" />
    <Compile Include="..\Shared\Storage\AzureTableDataManager.cs" Link="Storage\AzureTableDataManager.cs" />
    <Compile Include="..\Shared\Storage\AzureTableUtils.cs" Link="Storage\AzureTableUtils.cs" />
    <Compile Include="..\Shared\Utilities\ErrorCode.cs" Link="Utilities\ErrorCode.cs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="$(SourceRoot)src\Scynapse.Runtime\Scynapse.Runtime.csproj" />
    <PackageReference Include="Azure.Data.Tables" />
    <PackageReference Include="Azure.Core" />
    <PackageReference Include="Azure.Storage.Blobs" />
  </ItemGroup>

  <ItemGroup>
    <None Include="README.md" Pack="true" PackagePath="\" />
  </ItemGroup>
</Project>
