<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <PackageId>Genesa.Scynapse.Runtime</PackageId>
    <Title>Microsoft Scynapse Runtime</Title>
    <Description>Core runtime library of Microsoft Scynapse that hosts and executes grains within a silo.</Description>
    <TargetFrameworks>$(DefaultTargetFrameworks)</TargetFrameworks>
    <ScynapseBuildTimeCodeGen>true</ScynapseBuildTimeCodeGen>
    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="$(SourceRoot)src\\Scynapse.Core\Scynapse.Core.csproj" />
    <ProjectReference Include="$(SourceRoot)src\\Scynapse.Core.Abstractions\Scynapse.Core.Abstractions.csproj" />
    <ProjectReference Include="$(SourceRoot)src\\Scynapse.Serialization\Scynapse.Serialization.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="McMaster.NETCore.Plugins" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
    <PackageReference Include="Microsoft.Extensions.Logging" />
    <PackageReference Include="Microsoft.Extensions.Options" />
    <PackageReference Include="Microsoft.Extensions.Configuration" />
  </ItemGroup>

  <ItemGroup>
    <None Include="README.md" Pack="true" PackagePath="\" />
  </ItemGroup>

</Project>
