<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>UnitTests.GrainInterfaces</RootNamespace>
    <TargetFramework>$(MinTestTargetFramework)</TargetFramework>
    <ScynapseBuildTimeCodeGen>true</ScynapseBuildTimeCodeGen>
    <EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="$(SourceRoot)src\Scynapse.Streaming\Scynapse.Streaming.csproj" />
    <ProjectReference Include="$(SourceRoot)src\Scynapse.Serialization\Scynapse.Serialization.csproj" />
    <ProjectReference Include="$(SourceRoot)test\Misc\TestInterfaces\TestInterfaces.csproj" />
    <ProjectReference Include="$(SourceRoot)src\Scynapse.Reminders\Scynapse.Reminders.csproj" />
    <ProjectReference Include="$(SourceRoot)src\Scynapse.DurableJobs\Scynapse.DurableJobs.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="protobuf-net" />
  </ItemGroup>
</Project>
