//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Scynapse.Configuration
{
    public partial class AdoNetGrainDirectoryOptionsValidator : IConfigurationValidator
    {
        public AdoNetGrainDirectoryOptionsValidator(GrainDirectory.AdoNet.AdoNetGrainDirectoryOptions options, string name) { }

        public void ValidateConfiguration() { }
    }
}

namespace Scynapse.GrainDirectory.AdoNet
{
    public partial class AdoNetGrainDirectoryOptions
    {
        [Redact]
        [System.ComponentModel.DataAnnotations.Required]
        public string ConnectionString { get { throw null; } set { } }

        [System.ComponentModel.DataAnnotations.Required]
        public string Invariant { get { throw null; } set { } }
    }
}

namespace Scynapse.Hosting
{
    public static partial class AdoNetGrainDirectorySiloBuilderExtensions
    {
        public static ISiloBuilder AddAdoNetGrainDirectory(this ISiloBuilder builder, string name, System.Action<Microsoft.Extensions.Options.OptionsBuilder<GrainDirectory.AdoNet.AdoNetGrainDirectoryOptions>> configureOptions) { throw null; }

        public static ISiloBuilder AddAdoNetGrainDirectory(this ISiloBuilder builder, string name, System.Action<GrainDirectory.AdoNet.AdoNetGrainDirectoryOptions> configureOptions) { throw null; }

        public static ISiloBuilder UseAdoNetGrainDirectoryAsDefault(this ISiloBuilder builder, System.Action<Microsoft.Extensions.Options.OptionsBuilder<GrainDirectory.AdoNet.AdoNetGrainDirectoryOptions>> configureOptions) { throw null; }

        public static ISiloBuilder UseAdoNetGrainDirectoryAsDefault(this ISiloBuilder builder, System.Action<GrainDirectory.AdoNet.AdoNetGrainDirectoryOptions> configureOptions) { throw null; }
    }
}