<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <PackageId>Genesa.Scynapse.Streaming.NATS</PackageId>
    <Title>Microsoft Scynapse NATS Streaming Provider</Title>
    <Description>Microsoft Scynapse streaming provider backed by NATS</Description>
    <PackageTags>$(PackageTags) NATS</PackageTags>
    <DefineConstants>$(DefineConstants);SCYNAPSE_NATS</DefineConstants>
    <TargetFrameworks>$(DefaultTargetFrameworks)</TargetFrameworks>
    <AssemblyName>Scynapse.Streaming.NATS</AssemblyName>
    <RootNamespace>Scynapse.Streaming.NATS</RootNamespace>
    <ScynapseBuildTimeCodeGen>true</ScynapseBuildTimeCodeGen>
    <Nullable>enable</Nullable>
    <VersionSuffix Condition="$(VersionSuffix) != ''">$(VersionSuffix).alpha.1</VersionSuffix>
    <VersionSuffix Condition="$(VersionSuffix) == ''">alpha.1</VersionSuffix>
    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="$(SourceRoot)src\Scynapse.Streaming\Scynapse.Streaming.csproj" />
    <PackageReference Include="NATS.Net" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="NATS.Tests" />
  </ItemGroup>

  <ItemGroup>
    <None Include="README.md" Pack="true" PackagePath="\" />
  </ItemGroup>
</Project>
