//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Scynapse
{
    public static partial class GrainReminderExtensions
    {
        public static System.Threading.Tasks.Task<Runtime.IGrainReminder?> GetReminder(this Grain grain, string reminderName) { throw null; }

        public static System.Threading.Tasks.Task<Runtime.IGrainReminder?> GetReminder(this IGrainBase grain, string reminderName) { throw null; }

        public static System.Threading.Tasks.Task<System.Collections.Generic.List<Runtime.IGrainReminder>> GetReminders(this Grain grain) { throw null; }

        public static System.Threading.Tasks.Task<System.Collections.Generic.List<Runtime.IGrainReminder>> GetReminders(this IGrainBase grain) { throw null; }

        public static System.Threading.Tasks.Task<Runtime.IGrainReminder> RegisterOrUpdateReminder(this Grain grain, string reminderName, System.TimeSpan dueTime, System.TimeSpan period) { throw null; }

        public static System.Threading.Tasks.Task<Runtime.IGrainReminder> RegisterOrUpdateReminder(this IGrainBase grain, string reminderName, System.TimeSpan dueTime, System.TimeSpan period) { throw null; }

        public static System.Threading.Tasks.Task UnregisterReminder(this Grain grain, Runtime.IGrainReminder reminder) { throw null; }

        public static System.Threading.Tasks.Task UnregisterReminder(this IGrainBase grain, Runtime.IGrainReminder reminder) { throw null; }
    }

    public partial interface IRemindable : IGrain, Runtime.IAddressable
    {
        System.Threading.Tasks.Task ReceiveReminder(string reminderName, Runtime.TickStatus status);
    }

    public partial interface IReminderService : Services.IGrainService, ISystemTarget, Runtime.IAddressable
    {
        System.Threading.Tasks.Task<Runtime.IGrainReminder> GetReminder(Runtime.GrainId grainId, string reminderName);
        System.Threading.Tasks.Task<System.Collections.Generic.List<Runtime.IGrainReminder>> GetReminders(Runtime.GrainId grainId);
        System.Threading.Tasks.Task<Runtime.IGrainReminder> RegisterOrUpdateReminder(Runtime.GrainId grainId, string reminderName, System.TimeSpan dueTime, System.TimeSpan period);
        System.Threading.Tasks.Task Start();
        System.Threading.Tasks.Task Stop();
        System.Threading.Tasks.Task UnregisterReminder(Runtime.IGrainReminder reminder);
    }

    public partial interface IReminderTable
    {
        [System.Obsolete("Implement and use StartAsync instead")]
        System.Threading.Tasks.Task Init();
        System.Threading.Tasks.Task<ReminderEntry> ReadRow(Runtime.GrainId grainId, string reminderName);
        System.Threading.Tasks.Task<ReminderTableData> ReadRows(Runtime.GrainId grainId);
        System.Threading.Tasks.Task<ReminderTableData> ReadRows(uint begin, uint end);
        System.Threading.Tasks.Task<bool> RemoveRow(Runtime.GrainId grainId, string reminderName, string eTag);
        System.Threading.Tasks.Task StartAsync(System.Threading.CancellationToken cancellationToken = default);
        System.Threading.Tasks.Task StopAsync(System.Threading.CancellationToken cancellationToken = default);
        System.Threading.Tasks.Task TestOnlyClearTable();
        System.Threading.Tasks.Task<string> UpsertRow(ReminderEntry entry);
    }

    [GenerateSerializer]
    public sealed partial class ReminderEntry
    {
        [Id(4)]
        public string ETag { get { throw null; } set { } }

        [Id(0)]
        public Runtime.GrainId GrainId { get { throw null; } set { } }

        [Id(3)]
        public System.TimeSpan Period { get { throw null; } set { } }

        [Id(1)]
        public string ReminderName { get { throw null; } set { } }

        [Id(2)]
        public System.DateTime StartAt { get { throw null; } set { } }

        public override string ToString() { throw null; }
    }

    [GenerateSerializer]
    public sealed partial class ReminderTableData
    {
        public ReminderTableData() { }

        public ReminderTableData(ReminderEntry entry) { }

        public ReminderTableData(System.Collections.Generic.IEnumerable<ReminderEntry> list) { }

        [Id(0)]
        public System.Collections.Generic.IList<ReminderEntry> Reminders { get { throw null; } }

        public override string ToString() { throw null; }
    }
}

namespace Scynapse.Hosting
{
    public sealed partial class ReminderOptions
    {
        public System.TimeSpan InitializationTimeout { get { throw null; } set { } }

        public System.TimeSpan MinimumReminderPeriod { get { throw null; } set { } }

        public System.TimeSpan RefreshReminderListPeriod { get { throw null; } set { } }
    }

    public static partial class SiloBuilderReminderExtensions
    {
        public static void AddReminders(this Microsoft.Extensions.DependencyInjection.IServiceCollection services) { }

        public static ISiloBuilder AddReminders(this ISiloBuilder builder) { throw null; }
    }

    public static partial class SiloBuilderReminderMemoryExtensions
    {
        public static ISiloBuilder UseInMemoryReminderService(this ISiloBuilder builder) { throw null; }
    }
}

namespace Scynapse.Reminders
{
    public enum RSErrorCode
    {
        ReminderServiceBase = 102900,
        RS_Register_TableError = 102905,
        RS_Register_AlreadyRegistered = 102907,
        RS_Register_InvalidPeriod = 102908,
        RS_Register_NotRemindable = 102909,
        RS_NotResponsible = 102910,
        RS_Unregister_NotFoundLocally = 102911,
        RS_Unregister_TableError = 102912,
        RS_Table_Insert = 102913,
        RS_Table_Remove = 102914,
        RS_Tick_Delivery_Error = 102915,
        RS_Not_Started = 102916,
        RS_UnregisterGrain_TableError = 102917,
        RS_GrainBasedTable1 = 102918,
        RS_Factory1 = 102919,
        RS_FailedToReadTableAndStartTimer = 102920,
        RS_TableGrainInit1 = 102921,
        RS_TableGrainInit2 = 102922,
        RS_TableGrainInit3 = 102923,
        RS_GrainBasedTable2 = 102924,
        RS_ServiceStarting = 102925,
        RS_ServiceStarted = 102926,
        RS_ServiceStopping = 102927,
        RS_RegisterOrUpdate = 102928,
        RS_Unregister = 102929,
        RS_Stop = 102930,
        RS_RemoveFromTable = 102931,
        RS_GetReminder = 102932,
        RS_GetReminders = 102933,
        RS_RangeChanged = 102934,
        RS_LocalStop = 102935,
        RS_Started = 102936,
        RS_ServiceInitialLoadFailing = 102937,
        RS_ServiceInitialLoadFailed = 102938,
        RS_FastReminderInterval = 102939
    }
}

namespace Scynapse.Runtime
{
    public partial interface IGrainReminder
    {
        string ReminderName { get; }
    }

    [GenerateSerializer]
    public sealed partial class ReminderException : ScynapseException
    {
        [System.Obsolete]
        public ReminderException(System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context) { }

        public ReminderException(string message) { }
    }

    [GenerateSerializer]
    [Immutable]
    public readonly partial struct TickStatus
    {
        private readonly int _dummyPrimitive;
        public TickStatus(System.DateTime firstTickTime, System.TimeSpan period, System.DateTime timeStamp) { }

        [Id(2)]
        public System.DateTime CurrentTickTime { get { throw null; } }

        [Id(0)]
        public System.DateTime FirstTickTime { get { throw null; } }

        [Id(1)]
        public System.TimeSpan Period { get { throw null; } }

        public override readonly string ToString() { throw null; }
    }
}

namespace Scynapse.Timers
{
    public partial interface IReminderRegistry : Services.IGrainServiceClient<IReminderService>
    {
        System.Threading.Tasks.Task<Runtime.IGrainReminder> GetReminder(Runtime.GrainId callingGrainId, string reminderName);
        System.Threading.Tasks.Task<System.Collections.Generic.List<Runtime.IGrainReminder>> GetReminders(Runtime.GrainId callingGrainId);
        System.Threading.Tasks.Task<Runtime.IGrainReminder> RegisterOrUpdateReminder(Runtime.GrainId callingGrainId, string reminderName, System.TimeSpan dueTime, System.TimeSpan period);
        System.Threading.Tasks.Task UnregisterReminder(Runtime.GrainId callingGrainId, Runtime.IGrainReminder reminder);
    }
}

namespace ScynapseCodeGen.Scynapse
{
    [System.CodeDom.Compiler.GeneratedCode("ScynapseCodeGen", "9.0.0.0")]
    [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    public sealed partial class Codec_Invokable_IRemindable_GrainReference_6461BF2F : global::Scynapse.Serialization.Codecs.IFieldCodec<Invokable_IRemindable_GrainReference_6461BF2F>, global::Scynapse.Serialization.Codecs.IFieldCodec
    {
        public Codec_Invokable_IRemindable_GrainReference_6461BF2F(global::Scynapse.Serialization.Serializers.ICodecProvider codecProvider) { }

        public void Deserialize<TReaderInput>(ref global::Scynapse.Serialization.Buffers.Reader<TReaderInput> reader, Invokable_IRemindable_GrainReference_6461BF2F instance) { }

        public Invokable_IRemindable_GrainReference_6461BF2F ReadValue<TReaderInput>(ref global::Scynapse.Serialization.Buffers.Reader<TReaderInput> reader, global::Scynapse.Serialization.WireProtocol.Field field) { throw null; }

        public void Serialize<TBufferWriter>(ref global::Scynapse.Serialization.Buffers.Writer<TBufferWriter> writer, Invokable_IRemindable_GrainReference_6461BF2F instance)
            where TBufferWriter : System.Buffers.IBufferWriter<byte> { }

        public void WriteField<TBufferWriter>(ref global::Scynapse.Serialization.Buffers.Writer<TBufferWriter> writer, uint fieldIdDelta, System.Type expectedType, Invokable_IRemindable_GrainReference_6461BF2F value)
            where TBufferWriter : System.Buffers.IBufferWriter<byte> { }
    }

    [System.CodeDom.Compiler.GeneratedCode("ScynapseCodeGen", "9.0.0.0")]
    [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    public sealed partial class Codec_Invokable_IReminderService_GrainReference_1281C86D : global::Scynapse.Serialization.Codecs.IFieldCodec<Invokable_IReminderService_GrainReference_1281C86D>, global::Scynapse.Serialization.Codecs.IFieldCodec
    {
        public Codec_Invokable_IReminderService_GrainReference_1281C86D(global::Scynapse.Serialization.Serializers.ICodecProvider codecProvider) { }

        public void Deserialize<TReaderInput>(ref global::Scynapse.Serialization.Buffers.Reader<TReaderInput> reader, Invokable_IReminderService_GrainReference_1281C86D instance) { }

        public Invokable_IReminderService_GrainReference_1281C86D ReadValue<TReaderInput>(ref global::Scynapse.Serialization.Buffers.Reader<TReaderInput> reader, global::Scynapse.Serialization.WireProtocol.Field field) { throw null; }

        public void Serialize<TBufferWriter>(ref global::Scynapse.Serialization.Buffers.Writer<TBufferWriter> writer, Invokable_IReminderService_GrainReference_1281C86D instance)
            where TBufferWriter : System.Buffers.IBufferWriter<byte> { }

        public void WriteField<TBufferWriter>(ref global::Scynapse.Serialization.Buffers.Writer<TBufferWriter> writer, uint fieldIdDelta, System.Type expectedType, Invokable_IReminderService_GrainReference_1281C86D value)
            where TBufferWriter : System.Buffers.IBufferWriter<byte> { }
    }

    [System.CodeDom.Compiler.GeneratedCode("ScynapseCodeGen", "9.0.0.0")]
    [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    public sealed partial class Codec_Invokable_IReminderService_GrainReference_419EB51E : global::Scynapse.Serialization.Codecs.IFieldCodec<Invokable_IReminderService_GrainReference_419EB51E>, global::Scynapse.Serialization.Codecs.IFieldCodec
    {
        public Codec_Invokable_IReminderService_GrainReference_419EB51E(global::Scynapse.Serialization.Serializers.ICodecProvider codecProvider) { }

        public void Deserialize<TReaderInput>(ref global::Scynapse.Serialization.Buffers.Reader<TReaderInput> reader, Invokable_IReminderService_GrainReference_419EB51E instance) { }

        public Invokable_IReminderService_GrainReference_419EB51E ReadValue<TReaderInput>(ref global::Scynapse.Serialization.Buffers.Reader<TReaderInput> reader, global::Scynapse.Serialization.WireProtocol.Field field) { throw null; }

        public void Serialize<TBufferWriter>(ref global::Scynapse.Serialization.Buffers.Writer<TBufferWriter> writer, Invokable_IReminderService_GrainReference_419EB51E instance)
            where TBufferWriter : System.Buffers.IBufferWriter<byte> { }

        public void WriteField<TBufferWriter>(ref global::Scynapse.Serialization.Buffers.Writer<TBufferWriter> writer, uint fieldIdDelta, System.Type expectedType, Invokable_IReminderService_GrainReference_419EB51E value)
            where TBufferWriter : System.Buffers.IBufferWriter<byte> { }
    }

    [System.CodeDom.Compiler.GeneratedCode("ScynapseCodeGen", "9.0.0.0")]
    [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    public sealed partial class Codec_Invokable_IReminderService_GrainReference_5CF78F8A : global::Scynapse.Serialization.Codecs.IFieldCodec<Invokable_IReminderService_GrainReference_5CF78F8A>, global::Scynapse.Serialization.Codecs.IFieldCodec
    {
        public void Deserialize<TReaderInput>(ref global::Scynapse.Serialization.Buffers.Reader<TReaderInput> reader, Invokable_IReminderService_GrainReference_5CF78F8A instance) { }

        public Invokable_IReminderService_GrainReference_5CF78F8A ReadValue<TReaderInput>(ref global::Scynapse.Serialization.Buffers.Reader<TReaderInput> reader, global::Scynapse.Serialization.WireProtocol.Field field) { throw null; }

        public void Serialize<TBufferWriter>(ref global::Scynapse.Serialization.Buffers.Writer<TBufferWriter> writer, Invokable_IReminderService_GrainReference_5CF78F8A instance)
            where TBufferWriter : System.Buffers.IBufferWriter<byte> { }

        public void WriteField<TBufferWriter>(ref global::Scynapse.Serialization.Buffers.Writer<TBufferWriter> writer, uint fieldIdDelta, System.Type expectedType, Invokable_IReminderService_GrainReference_5CF78F8A value)
            where TBufferWriter : System.Buffers.IBufferWriter<byte> { }
    }

    [System.CodeDom.Compiler.GeneratedCode("ScynapseCodeGen", "9.0.0.0")]
    [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    public sealed partial class Codec_Invokable_IReminderService_GrainReference_A7AF84A8 : global::Scynapse.Serialization.Codecs.IFieldCodec<Invokable_IReminderService_GrainReference_A7AF84A8>, global::Scynapse.Serialization.Codecs.IFieldCodec
    {
        public Codec_Invokable_IReminderService_GrainReference_A7AF84A8(global::Scynapse.Serialization.Serializers.ICodecProvider codecProvider) { }

        public void Deserialize<TReaderInput>(ref global::Scynapse.Serialization.Buffers.Reader<TReaderInput> reader, Invokable_IReminderService_GrainReference_A7AF84A8 instance) { }

        public Invokable_IReminderService_GrainReference_A7AF84A8 ReadValue<TReaderInput>(ref global::Scynapse.Serialization.Buffers.Reader<TReaderInput> reader, global::Scynapse.Serialization.WireProtocol.Field field) { throw null; }

        public void Serialize<TBufferWriter>(ref global::Scynapse.Serialization.Buffers.Writer<TBufferWriter> writer, Invokable_IReminderService_GrainReference_A7AF84A8 instance)
            where TBufferWriter : System.Buffers.IBufferWriter<byte> { }

        public void WriteField<TBufferWriter>(ref global::Scynapse.Serialization.Buffers.Writer<TBufferWriter> writer, uint fieldIdDelta, System.Type expectedType, Invokable_IReminderService_GrainReference_A7AF84A8 value)
            where TBufferWriter : System.Buffers.IBufferWriter<byte> { }
    }

    [System.CodeDom.Compiler.GeneratedCode("ScynapseCodeGen", "9.0.0.0")]
    [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    public sealed partial class Codec_Invokable_IReminderService_GrainReference_AC622EEB : global::Scynapse.Serialization.Codecs.IFieldCodec<Invokable_IReminderService_GrainReference_AC622EEB>, global::Scynapse.Serialization.Codecs.IFieldCodec
    {
        public Codec_Invokable_IReminderService_GrainReference_AC622EEB(global::Scynapse.Serialization.Serializers.ICodecProvider codecProvider) { }

        public void Deserialize<TReaderInput>(ref global::Scynapse.Serialization.Buffers.Reader<TReaderInput> reader, Invokable_IReminderService_GrainReference_AC622EEB instance) { }

        public Invokable_IReminderService_GrainReference_AC622EEB ReadValue<TReaderInput>(ref global::Scynapse.Serialization.Buffers.Reader<TReaderInput> reader, global::Scynapse.Serialization.WireProtocol.Field field) { throw null; }

        public void Serialize<TBufferWriter>(ref global::Scynapse.Serialization.Buffers.Writer<TBufferWriter> writer, Invokable_IReminderService_GrainReference_AC622EEB instance)
            where TBufferWriter : System.Buffers.IBufferWriter<byte> { }

        public void WriteField<TBufferWriter>(ref global::Scynapse.Serialization.Buffers.Writer<TBufferWriter> writer, uint fieldIdDelta, System.Type expectedType, Invokable_IReminderService_GrainReference_AC622EEB value)
            where TBufferWriter : System.Buffers.IBufferWriter<byte> { }
    }

    [System.CodeDom.Compiler.GeneratedCode("ScynapseCodeGen", "9.0.0.0")]
    [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    public sealed partial class Codec_Invokable_IReminderService_GrainReference_DCFCA00D : global::Scynapse.Serialization.Codecs.IFieldCodec<Invokable_IReminderService_GrainReference_DCFCA00D>, global::Scynapse.Serialization.Codecs.IFieldCodec
    {
        public void Deserialize<TReaderInput>(ref global::Scynapse.Serialization.Buffers.Reader<TReaderInput> reader, Invokable_IReminderService_GrainReference_DCFCA00D instance) { }

        public Invokable_IReminderService_GrainReference_DCFCA00D ReadValue<TReaderInput>(ref global::Scynapse.Serialization.Buffers.Reader<TReaderInput> reader, global::Scynapse.Serialization.WireProtocol.Field field) { throw null; }

        public void Serialize<TBufferWriter>(ref global::Scynapse.Serialization.Buffers.Writer<TBufferWriter> writer, Invokable_IReminderService_GrainReference_DCFCA00D instance)
            where TBufferWriter : System.Buffers.IBufferWriter<byte> { }

        public void WriteField<TBufferWriter>(ref global::Scynapse.Serialization.Buffers.Writer<TBufferWriter> writer, uint fieldIdDelta, System.Type expectedType, Invokable_IReminderService_GrainReference_DCFCA00D value)
            where TBufferWriter : System.Buffers.IBufferWriter<byte> { }
    }

    [System.CodeDom.Compiler.GeneratedCode("ScynapseCodeGen", "9.0.0.0")]
    [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    public sealed partial class Codec_ReminderEntry : global::Scynapse.Serialization.Codecs.IFieldCodec<global::Scynapse.ReminderEntry>, global::Scynapse.Serialization.Codecs.IFieldCodec
    {
        public Codec_ReminderEntry(global::Scynapse.Serialization.Serializers.ICodecProvider codecProvider) { }

        public void Deserialize<TReaderInput>(ref global::Scynapse.Serialization.Buffers.Reader<TReaderInput> reader, global::Scynapse.ReminderEntry instance) { }

        public global::Scynapse.ReminderEntry ReadValue<TReaderInput>(ref global::Scynapse.Serialization.Buffers.Reader<TReaderInput> reader, global::Scynapse.Serialization.WireProtocol.Field field) { throw null; }

        public void Serialize<TBufferWriter>(ref global::Scynapse.Serialization.Buffers.Writer<TBufferWriter> writer, global::Scynapse.ReminderEntry instance)
            where TBufferWriter : System.Buffers.IBufferWriter<byte> { }

        public void WriteField<TBufferWriter>(ref global::Scynapse.Serialization.Buffers.Writer<TBufferWriter> writer, uint fieldIdDelta, System.Type expectedType, global::Scynapse.ReminderEntry value)
            where TBufferWriter : System.Buffers.IBufferWriter<byte> { }
    }

    [System.CodeDom.Compiler.GeneratedCode("ScynapseCodeGen", "9.0.0.0")]
    [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    public sealed partial class Codec_ReminderTableData : global::Scynapse.Serialization.Codecs.IFieldCodec<global::Scynapse.ReminderTableData>, global::Scynapse.Serialization.Codecs.IFieldCodec
    {
        public Codec_ReminderTableData(global::Scynapse.Serialization.Serializers.ICodecProvider codecProvider) { }

        public void Deserialize<TReaderInput>(ref global::Scynapse.Serialization.Buffers.Reader<TReaderInput> reader, global::Scynapse.ReminderTableData instance) { }

        public global::Scynapse.ReminderTableData ReadValue<TReaderInput>(ref global::Scynapse.Serialization.Buffers.Reader<TReaderInput> reader, global::Scynapse.Serialization.WireProtocol.Field field) { throw null; }

        public void Serialize<TBufferWriter>(ref global::Scynapse.Serialization.Buffers.Writer<TBufferWriter> writer, global::Scynapse.ReminderTableData instance)
            where TBufferWriter : System.Buffers.IBufferWriter<byte> { }

        public void WriteField<TBufferWriter>(ref global::Scynapse.Serialization.Buffers.Writer<TBufferWriter> writer, uint fieldIdDelta, System.Type expectedType, global::Scynapse.ReminderTableData value)
            where TBufferWriter : System.Buffers.IBufferWriter<byte> { }
    }

    [System.CodeDom.Compiler.GeneratedCode("ScynapseCodeGen", "9.0.0.0")]
    [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    public sealed partial class Copier_Invokable_IRemindable_GrainReference_6461BF2F : global::Scynapse.Serialization.Cloning.IDeepCopier<Invokable_IRemindable_GrainReference_6461BF2F>, global::Scynapse.Serialization.Cloning.IDeepCopier
    {
        public Invokable_IRemindable_GrainReference_6461BF2F DeepCopy(Invokable_IRemindable_GrainReference_6461BF2F original, global::Scynapse.Serialization.Cloning.CopyContext context) { throw null; }
    }

    [System.CodeDom.Compiler.GeneratedCode("ScynapseCodeGen", "9.0.0.0")]
    [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    public sealed partial class Copier_Invokable_IReminderService_GrainReference_1281C86D : global::Scynapse.Serialization.Cloning.IDeepCopier<Invokable_IReminderService_GrainReference_1281C86D>, global::Scynapse.Serialization.Cloning.IDeepCopier
    {
        public Invokable_IReminderService_GrainReference_1281C86D DeepCopy(Invokable_IReminderService_GrainReference_1281C86D original, global::Scynapse.Serialization.Cloning.CopyContext context) { throw null; }
    }

    [System.CodeDom.Compiler.GeneratedCode("ScynapseCodeGen", "9.0.0.0")]
    [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    public sealed partial class Copier_Invokable_IReminderService_GrainReference_419EB51E : global::Scynapse.Serialization.Cloning.IDeepCopier<Invokable_IReminderService_GrainReference_419EB51E>, global::Scynapse.Serialization.Cloning.IDeepCopier
    {
        public Invokable_IReminderService_GrainReference_419EB51E DeepCopy(Invokable_IReminderService_GrainReference_419EB51E original, global::Scynapse.Serialization.Cloning.CopyContext context) { throw null; }
    }

    [System.CodeDom.Compiler.GeneratedCode("ScynapseCodeGen", "9.0.0.0")]
    [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    public sealed partial class Copier_Invokable_IReminderService_GrainReference_5CF78F8A : global::Scynapse.Serialization.Cloning.IDeepCopier<Invokable_IReminderService_GrainReference_5CF78F8A>, global::Scynapse.Serialization.Cloning.IDeepCopier
    {
        public Invokable_IReminderService_GrainReference_5CF78F8A DeepCopy(Invokable_IReminderService_GrainReference_5CF78F8A original, global::Scynapse.Serialization.Cloning.CopyContext context) { throw null; }
    }

    [System.CodeDom.Compiler.GeneratedCode("ScynapseCodeGen", "9.0.0.0")]
    [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    public sealed partial class Copier_Invokable_IReminderService_GrainReference_A7AF84A8 : global::Scynapse.Serialization.Cloning.IDeepCopier<Invokable_IReminderService_GrainReference_A7AF84A8>, global::Scynapse.Serialization.Cloning.IDeepCopier
    {
        public Copier_Invokable_IReminderService_GrainReference_A7AF84A8(global::Scynapse.Serialization.Serializers.ICodecProvider codecProvider) { }

        public Invokable_IReminderService_GrainReference_A7AF84A8 DeepCopy(Invokable_IReminderService_GrainReference_A7AF84A8 original, global::Scynapse.Serialization.Cloning.CopyContext context) { throw null; }
    }

    [System.CodeDom.Compiler.GeneratedCode("ScynapseCodeGen", "9.0.0.0")]
    [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    public sealed partial class Copier_Invokable_IReminderService_GrainReference_AC622EEB : global::Scynapse.Serialization.Cloning.IDeepCopier<Invokable_IReminderService_GrainReference_AC622EEB>, global::Scynapse.Serialization.Cloning.IDeepCopier
    {
        public Invokable_IReminderService_GrainReference_AC622EEB DeepCopy(Invokable_IReminderService_GrainReference_AC622EEB original, global::Scynapse.Serialization.Cloning.CopyContext context) { throw null; }
    }

    [System.CodeDom.Compiler.GeneratedCode("ScynapseCodeGen", "9.0.0.0")]
    [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    public sealed partial class Copier_Invokable_IReminderService_GrainReference_DCFCA00D : global::Scynapse.Serialization.Cloning.IDeepCopier<Invokable_IReminderService_GrainReference_DCFCA00D>, global::Scynapse.Serialization.Cloning.IDeepCopier
    {
        public Invokable_IReminderService_GrainReference_DCFCA00D DeepCopy(Invokable_IReminderService_GrainReference_DCFCA00D original, global::Scynapse.Serialization.Cloning.CopyContext context) { throw null; }
    }

    [System.CodeDom.Compiler.GeneratedCode("ScynapseCodeGen", "9.0.0.0")]
    [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    public sealed partial class Copier_ReminderEntry : global::Scynapse.Serialization.Cloning.IDeepCopier<global::Scynapse.ReminderEntry>, global::Scynapse.Serialization.Cloning.IDeepCopier
    {
        public global::Scynapse.ReminderEntry DeepCopy(global::Scynapse.ReminderEntry original, global::Scynapse.Serialization.Cloning.CopyContext context) { throw null; }
    }

    [System.CodeDom.Compiler.GeneratedCode("ScynapseCodeGen", "9.0.0.0")]
    [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    public sealed partial class Copier_ReminderTableData : global::Scynapse.Serialization.Cloning.IDeepCopier<global::Scynapse.ReminderTableData>, global::Scynapse.Serialization.Cloning.IDeepCopier
    {
        public Copier_ReminderTableData(global::Scynapse.Serialization.Serializers.ICodecProvider codecProvider) { }

        public global::Scynapse.ReminderTableData DeepCopy(global::Scynapse.ReminderTableData original, global::Scynapse.Serialization.Cloning.CopyContext context) { throw null; }
    }

    [System.CodeDom.Compiler.GeneratedCode("ScynapseCodeGen", "9.0.0.0")]
    [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    [global::Scynapse.CompoundTypeAlias(new[] { "inv", typeof(global::Scynapse.Runtime.GrainReference), typeof(global::Scynapse.IRemindable), "6461BF2F" })]
    public sealed partial class Invokable_IRemindable_GrainReference_6461BF2F : global::Scynapse.Runtime.TaskRequest
    {
        public string arg0;
        public global::Scynapse.Runtime.TickStatus arg1;
        public override void Dispose() { }

        public override string GetActivityName() { throw null; }

        public override object GetArgument(int index) { throw null; }

        public override int GetArgumentCount() { throw null; }

        public override string GetInterfaceName() { throw null; }

        public override System.Type GetInterfaceType() { throw null; }

        public override System.Reflection.MethodInfo GetMethod() { throw null; }

        public override string GetMethodName() { throw null; }

        public override object GetTarget() { throw null; }

        protected override System.Threading.Tasks.Task InvokeInner() { throw null; }

        public override void SetArgument(int index, object value) { }

        public override void SetTarget(global::Scynapse.Serialization.Invocation.ITargetHolder holder) { }
    }

    [System.CodeDom.Compiler.GeneratedCode("ScynapseCodeGen", "9.0.0.0")]
    [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    [global::Scynapse.CompoundTypeAlias(new[] { "inv", typeof(global::Scynapse.Runtime.GrainReference), typeof(global::Scynapse.IReminderService), "1281C86D" })]
    public sealed partial class Invokable_IReminderService_GrainReference_1281C86D : global::Scynapse.Runtime.TaskRequest<global::Scynapse.Runtime.IGrainReminder>
    {
        public global::Scynapse.Runtime.GrainId arg0;
        public string arg1;
        public System.TimeSpan arg2;
        public System.TimeSpan arg3;
        public override void Dispose() { }

        public override string GetActivityName() { throw null; }

        public override object GetArgument(int index) { throw null; }

        public override int GetArgumentCount() { throw null; }

        public override string GetInterfaceName() { throw null; }

        public override System.Type GetInterfaceType() { throw null; }

        public override System.Reflection.MethodInfo GetMethod() { throw null; }

        public override string GetMethodName() { throw null; }

        public override object GetTarget() { throw null; }

        protected override System.Threading.Tasks.Task<global::Scynapse.Runtime.IGrainReminder> InvokeInner() { throw null; }

        public override void SetArgument(int index, object value) { }

        public override void SetTarget(global::Scynapse.Serialization.Invocation.ITargetHolder holder) { }
    }

    [System.CodeDom.Compiler.GeneratedCode("ScynapseCodeGen", "9.0.0.0")]
    [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    [global::Scynapse.CompoundTypeAlias(new[] { "inv", typeof(global::Scynapse.Runtime.GrainReference), typeof(global::Scynapse.IReminderService), "419EB51E" })]
    public sealed partial class Invokable_IReminderService_GrainReference_419EB51E : global::Scynapse.Runtime.TaskRequest<System.Collections.Generic.List<global::Scynapse.Runtime.IGrainReminder>>
    {
        public global::Scynapse.Runtime.GrainId arg0;
        public override void Dispose() { }

        public override string GetActivityName() { throw null; }

        public override object GetArgument(int index) { throw null; }

        public override int GetArgumentCount() { throw null; }

        public override string GetInterfaceName() { throw null; }

        public override System.Type GetInterfaceType() { throw null; }

        public override System.Reflection.MethodInfo GetMethod() { throw null; }

        public override string GetMethodName() { throw null; }

        public override object GetTarget() { throw null; }

        protected override System.Threading.Tasks.Task<System.Collections.Generic.List<global::Scynapse.Runtime.IGrainReminder>> InvokeInner() { throw null; }

        public override void SetArgument(int index, object value) { }

        public override void SetTarget(global::Scynapse.Serialization.Invocation.ITargetHolder holder) { }
    }

    [System.CodeDom.Compiler.GeneratedCode("ScynapseCodeGen", "9.0.0.0")]
    [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    [global::Scynapse.CompoundTypeAlias(new[] { "inv", typeof(global::Scynapse.Runtime.GrainReference), typeof(global::Scynapse.IReminderService), "5CF78F8A" })]
    public sealed partial class Invokable_IReminderService_GrainReference_5CF78F8A : global::Scynapse.Runtime.TaskRequest
    {
        public override void Dispose() { }

        public override string GetActivityName() { throw null; }

        public override string GetInterfaceName() { throw null; }

        public override System.Type GetInterfaceType() { throw null; }

        public override System.Reflection.MethodInfo GetMethod() { throw null; }

        public override string GetMethodName() { throw null; }

        public override object GetTarget() { throw null; }

        protected override System.Threading.Tasks.Task InvokeInner() { throw null; }

        public override void SetTarget(global::Scynapse.Serialization.Invocation.ITargetHolder holder) { }
    }

    [System.CodeDom.Compiler.GeneratedCode("ScynapseCodeGen", "9.0.0.0")]
    [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    [global::Scynapse.CompoundTypeAlias(new[] { "inv", typeof(global::Scynapse.Runtime.GrainReference), typeof(global::Scynapse.IReminderService), "A7AF84A8" })]
    public sealed partial class Invokable_IReminderService_GrainReference_A7AF84A8 : global::Scynapse.Runtime.TaskRequest
    {
        public global::Scynapse.Runtime.IGrainReminder arg0;
        public override void Dispose() { }

        public override string GetActivityName() { throw null; }

        public override object GetArgument(int index) { throw null; }

        public override int GetArgumentCount() { throw null; }

        public override string GetInterfaceName() { throw null; }

        public override System.Type GetInterfaceType() { throw null; }

        public override System.Reflection.MethodInfo GetMethod() { throw null; }

        public override string GetMethodName() { throw null; }

        public override object GetTarget() { throw null; }

        protected override System.Threading.Tasks.Task InvokeInner() { throw null; }

        public override void SetArgument(int index, object value) { }

        public override void SetTarget(global::Scynapse.Serialization.Invocation.ITargetHolder holder) { }
    }

    [System.CodeDom.Compiler.GeneratedCode("ScynapseCodeGen", "9.0.0.0")]
    [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    [global::Scynapse.CompoundTypeAlias(new[] { "inv", typeof(global::Scynapse.Runtime.GrainReference), typeof(global::Scynapse.IReminderService), "AC622EEB" })]
    public sealed partial class Invokable_IReminderService_GrainReference_AC622EEB : global::Scynapse.Runtime.TaskRequest<global::Scynapse.Runtime.IGrainReminder>
    {
        public global::Scynapse.Runtime.GrainId arg0;
        public string arg1;
        public override void Dispose() { }

        public override string GetActivityName() { throw null; }

        public override object GetArgument(int index) { throw null; }

        public override int GetArgumentCount() { throw null; }

        public override string GetInterfaceName() { throw null; }

        public override System.Type GetInterfaceType() { throw null; }

        public override System.Reflection.MethodInfo GetMethod() { throw null; }

        public override string GetMethodName() { throw null; }

        public override object GetTarget() { throw null; }

        protected override System.Threading.Tasks.Task<global::Scynapse.Runtime.IGrainReminder> InvokeInner() { throw null; }

        public override void SetArgument(int index, object value) { }

        public override void SetTarget(global::Scynapse.Serialization.Invocation.ITargetHolder holder) { }
    }

    [System.CodeDom.Compiler.GeneratedCode("ScynapseCodeGen", "9.0.0.0")]
    [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    [global::Scynapse.CompoundTypeAlias(new[] { "inv", typeof(global::Scynapse.Runtime.GrainReference), typeof(global::Scynapse.IReminderService), "DCFCA00D" })]
    public sealed partial class Invokable_IReminderService_GrainReference_DCFCA00D : global::Scynapse.Runtime.TaskRequest
    {
        public override void Dispose() { }

        public override string GetActivityName() { throw null; }

        public override string GetInterfaceName() { throw null; }

        public override System.Type GetInterfaceType() { throw null; }

        public override System.Reflection.MethodInfo GetMethod() { throw null; }

        public override string GetMethodName() { throw null; }

        public override object GetTarget() { throw null; }

        protected override System.Threading.Tasks.Task InvokeInner() { throw null; }

        public override void SetTarget(global::Scynapse.Serialization.Invocation.ITargetHolder holder) { }
    }
}

namespace ScynapseCodeGen.Scynapse.Runtime
{
    [System.CodeDom.Compiler.GeneratedCode("ScynapseCodeGen", "9.0.0.0")]
    [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    public sealed partial class Codec_ReminderException : global::Scynapse.Serialization.Codecs.IFieldCodec<global::Scynapse.Runtime.ReminderException>, global::Scynapse.Serialization.Codecs.IFieldCodec
    {
        public Codec_ReminderException(global::Scynapse.Serialization.Serializers.ICodecProvider codecProvider, global::Scynapse.Serialization.Activators.IActivator<global::Scynapse.Runtime.ReminderException> _activator) { }

        public void Deserialize<TReaderInput>(ref global::Scynapse.Serialization.Buffers.Reader<TReaderInput> reader, global::Scynapse.Runtime.ReminderException instance) { }

        public global::Scynapse.Runtime.ReminderException ReadValue<TReaderInput>(ref global::Scynapse.Serialization.Buffers.Reader<TReaderInput> reader, global::Scynapse.Serialization.WireProtocol.Field field) { throw null; }

        public void Serialize<TBufferWriter>(ref global::Scynapse.Serialization.Buffers.Writer<TBufferWriter> writer, global::Scynapse.Runtime.ReminderException instance)
            where TBufferWriter : System.Buffers.IBufferWriter<byte> { }

        public void WriteField<TBufferWriter>(ref global::Scynapse.Serialization.Buffers.Writer<TBufferWriter> writer, uint fieldIdDelta, System.Type expectedType, global::Scynapse.Runtime.ReminderException value)
            where TBufferWriter : System.Buffers.IBufferWriter<byte> { }
    }

    [System.CodeDom.Compiler.GeneratedCode("ScynapseCodeGen", "9.0.0.0")]
    [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    public sealed partial class Codec_TickStatus : global::Scynapse.Serialization.Codecs.IFieldCodec<global::Scynapse.Runtime.TickStatus>, global::Scynapse.Serialization.Codecs.IFieldCodec, global::Scynapse.Serialization.Serializers.IValueSerializer<global::Scynapse.Runtime.TickStatus>, global::Scynapse.Serialization.Serializers.IValueSerializer
    {
        public void Deserialize<TReaderInput>(ref global::Scynapse.Serialization.Buffers.Reader<TReaderInput> reader, scoped ref global::Scynapse.Runtime.TickStatus instance) { }

        public global::Scynapse.Runtime.TickStatus ReadValue<TReaderInput>(ref global::Scynapse.Serialization.Buffers.Reader<TReaderInput> reader, global::Scynapse.Serialization.WireProtocol.Field field) { throw null; }

        public void Serialize<TBufferWriter>(ref global::Scynapse.Serialization.Buffers.Writer<TBufferWriter> writer, scoped ref global::Scynapse.Runtime.TickStatus instance)
            where TBufferWriter : System.Buffers.IBufferWriter<byte> { }

        public void WriteField<TBufferWriter>(ref global::Scynapse.Serialization.Buffers.Writer<TBufferWriter> writer, uint fieldIdDelta, System.Type expectedType, global::Scynapse.Runtime.TickStatus value)
            where TBufferWriter : System.Buffers.IBufferWriter<byte> { }
    }

    [System.CodeDom.Compiler.GeneratedCode("ScynapseCodeGen", "9.0.0.0")]
    [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    public sealed partial class Copier_ReminderException : global::Scynapse.Serialization.GeneratedCodeHelpers.ScynapseGeneratedCodeHelper.ExceptionCopier<global::Scynapse.Runtime.ReminderException, global::Scynapse.Runtime.ScynapseException>
    {
        public Copier_ReminderException(global::Scynapse.Serialization.Serializers.ICodecProvider codecProvider) : base(default(Serialization.Serializers.ICodecProvider)!) { }
    }
}