<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <ScynapseBuildTimeCodeGen>true</ScynapseBuildTimeCodeGen>
    <ServerGarbageCollection>true</ServerGarbageCollection>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\src\Azure\Scynapse.Clustering.AzureStorage\Scynapse.Clustering.AzureStorage.csproj" />
    <ProjectReference Include="..\..\..\src\Scynapse.Server\Scynapse.Server.csproj" />
    <ProjectReference Include="..\..\..\src\Scynapse.TestingHost\Scynapse.TestingHost.csproj" />
    <ProjectReference Include="..\ChaoticCluster.ServiceDefaults\ChaoticCluster.ServiceDefaults.csproj" />
  </ItemGroup>

</Project>
