<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFrameworks>$(TestTargetFrameworks)</TargetFrameworks>
    <ScynapseBuildTimeCodeGen>true</ScynapseBuildTimeCodeGen>
    <OutputPath Condition=" '$(DistributedTestsOutputPath)'!='' ">$(DistributedTestsOutputPath)/DistributedTests.Client</OutputPath>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="..\secrets.json" Link="secrets.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\src\Azure\Scynapse.Clustering.AzureStorage\Scynapse.Clustering.AzureStorage.csproj" />
    <ProjectReference Include="..\..\..\src\Scynapse.Client\Scynapse.Client.csproj" />
    <ProjectReference Include="..\DistributedTests.Common\DistributedTests.Common.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Crank.EventSources" />
    <PackageReference Include="System.CommandLine" />
    <PackageReference Include="Microsoft.Extensions.Hosting" />
  </ItemGroup>

</Project>
