<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <ScynapseBuildTimeCodeGen>true</ScynapseBuildTimeCodeGen>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="$(SourceRoot)src\Scynapse.Transactions\Scynapse.Transactions.csproj" />
    <ProjectReference Include="$(SourceRoot)test\Grains\BenchmarkGrainInterfaces\BenchmarkGrainInterfaces.csproj" />
  </ItemGroup>
</Project>
