<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>$(TestTargetFrameworks)</TargetFrameworks>
    <ScynapseBuildTimeCodeGen>true</ScynapseBuildTimeCodeGen>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="$(SourceRoot)src\Scynapse.Streaming\Scynapse.Streaming.csproj" />
    <ProjectReference Include="$(SourceRoot)src\Scynapse.Core.Abstractions\Scynapse.Core.Abstractions.csproj" />
    <ProjectReference Include="$(SourceRoot)src\Scynapse.Reminders\Scynapse.Reminders.csproj" />
    <ProjectReference Include="$(SourceRoot)test\DistributedTests\DistributedTests.Common\DistributedTests.Common.csproj" />
  </ItemGroup>
  
</Project>
