<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>$(TestTargetFrameworks)</TargetFrameworks>
    <ScynapseBuildTimeCodeGen>true</ScynapseBuildTimeCodeGen>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="System.Diagnostics.PerformanceCounter" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="$(SourceRoot)src\Redis\Scynapse.Clustering.Redis\Scynapse.Clustering.Redis.csproj" />
    <ProjectReference Include="$(SourceRoot)src\Redis\Scynapse.Reminders.Redis\Scynapse.Reminders.Redis.csproj" />
    <ProjectReference Include="$(SourceRoot)src\Redis\Scynapse.Persistence.Redis\Scynapse.Persistence.Redis.csproj" />
    <ProjectReference Include="$(SourceRoot)src\Redis\Scynapse.GrainDirectory.Redis\Scynapse.GrainDirectory.Redis.csproj" />
    <ProjectReference Include="$(SourceRoot)test\TesterInternal\TesterInternal.csproj" />

  </ItemGroup>

</Project>
